---
title: "python_test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

```{r}
```

```{python}
import numpy as np
x_in_script = np.array([4,5,6])
yin_script = np.square(x_in_script)
print(x_in_script[1])
import pandas
```

```{r}
load("../data/genfo.rda")

chr_sizes <- readr::read_tsv("../data-raw/chr_list_noMT_HS.txt")

total_genes <- nrow(genfo)
```


```{r}
library(reticulate)
#source_python("../python/simple_python_script.py")
source_python("../python/generate_random_positions.py")
```

```{r}
py$closest_genes
```


```{r}
py$x_squared
```

```{python}
import pandas
chr_lengths = pandas.read_csv("D:/GObiases_human/data-raw/chr_list_noMT.csv", 
    header= None, 
    names = ("chr", "length"))
print(chr_lengths)
```

```{r}
py$chr_lengths$chr
py$chr_lengths$length
# source_python("../python/generate_random_positions.py")
# chr_file <- "../data-raw/chr_list_noMT.txt"
# chr_py <- read_chr_sizes(chr_file)
# chr_py
```


